return {
  ensure_installed = {
    "beautysh",
    "clang-format",
    "clangd",
    "css-lsp",
    "deno",
    "eslint-lsp",
    "html-lsp",
    "lua-language-server",
    "mdx-analyzer",
    "prettier",
    "ruff",
    "rust-analyzer",
    "solidity",
    "solhint",
    "sqlfmt",
    "stylua",
    "typescript-language-server",
    "tailwindcss-language-server",
  },
}
