require("util")
require("options")

require("plugins")
require("lsp")

require("config.treesitter")
require("config.ui")
require("config.compe")
require("config.misc")
require("config.lightbulb")
require("config.autocommands")
require("config.gitsigns")
require("config.blankline")
require("config.nvimtree")
require("config.bufferline")
require("config.autopairs")
require("config.telescope")
require("config.mappings")
