require('util')
require('options')

require('plugins')

require('config.treesitter')
require('config.lsp')
require('config.ui')
require('config.compe')
require('config.lspkind')
require('config.misc')
require('config.lightbulb')
require('config.autocommands')
require('config.blankline')
require('config.nvimtree')
require('config.bufferline')
require('config.autopairs')
require('config.telescope')
require('config.mappings')

